blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/Nigel1992/plugin.video.iptvxc/discussions
    about: Please ask questions or request support in GitHub Discussions.